---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hosted-redislabs-exporter
    monitoring: prometheus
  name: hosted-redislabs-exporter
  namespace: oe-redis-exporter-hosted
spec:
  clusterIP: None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9121
    protocol: TCP
    targetPort: 9121
  publishNotReadyAddresses: true
  selector:
    app: hosted-redislabs-exporter
  sessionAffinity: None
  type: ClusterIP
