apiVersion: v1
kind: Secret
metadata:
    name: otel-secret
    namespace: oe-otel
type: Opaque
data:
    OTLP_USER: ENC[AES256_GCM,data:0vRU+4NsVQbE4fsI,iv:Tv12ohJ78OWg2h8nM5yVC3mHPY1swrs/YmfZy9LA4+4=,tag:7FVE1fR6by/naHt4PIjMeg==,type:str]
    OTLP_PASSWORD: ENC[AES256_GCM,data:jTDUyuHqKPQ+A6JgJdLzy2/MKVEf1wWSABAgraLO6eW3Cb2vW0nCBZOiYRs=,iv:6R2gN9L5iHL7yQDp20WLULzBcPy28Boq8eoFt9xYqPo=,tag:sTCHIPOM/dNVODykcLfDPg==,type:str]
    APM_SERVER_TOKEN: ENC[AES256_GCM,data:3SllNh296DUhaTjMqvbX6CQuDx3OV56aZUFSRaSHGOyqj9KOuTS8Eg==,iv:AGVBZo5aneRxUOrBPJkNRHOrWTzjxBQgJ7JezTE4d24=,tag:O5XD1EDWgaxItCcW5RQuww==,type:str]
sops:
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2025-07-17T18:31:55Z"
          enc: YfR8qdZb2bIa6O0m390Qku_fbdrhQM4hmIpVnvt8w7qYHbMqBC8Wzn632Iw8o8CuGhhJmBP9O-sGeF09nTfuRCed6ZAQkRnVNpLCler1uitBtvGbWFIY1FSV7Ah3dXGsG-t7D1BhEtnVNUcigsk7MEzk9Q7XGNFdLRny09DkcLI9H-Bt9sQD7mAEI1L9P3HyIGKY_SPs8xAoIcBv5NwnOnPpGzB1WiDNeVFew6kRHs9rvZc23FKEr3065cFrZ0omP3P_x2jiS0a9g_jM8XwXR_qeNOJXO3UydVrc7PsfmzH9P4vP09bZBd26Hc4sNDKFHVySB-jzHQJvYLJk3j8steJqTNizD5z38qRo81bmAMwbaMsCVyWkE7dSHT0V9Ytu9bstQBQyse1jXhAQhbFJwMRIozZAgkBmgawlkJoJCJqhhL8a_Vy8ZuSEBYnEPQCvktaJWIcFv52AFnZl1vKnE1OILsLGGp8i75UC5nRk-TOQkUvf1Xaq0NSkI7IwcE3dRcxawjOIXCvK3yotndwrL1naFFrc5kK4C8Z6wSnKNJVqqiklxg05U-ldM0k8TiL45zaaW3-PymUJAC8MZ-et7KF37WTBsJsbU72LNQPA_VYdNBhuaWt7bbY2aLQebg8Ef1QoLa0aAZAw_hruGEIxzLkE2ToZP2lGMx0n6L3Dq2g
    lastmodified: "2025-07-17T18:31:59Z"
    mac: ENC[AES256_GCM,data:qFsiPrO6O2+1Jd/BHM0lllVPFCljAXJm/F7KhhIO/2Y3fTtDSkQTmXNR/J91+03kY7z0B/XH9aC5pJsf7KHKJPAM3uXiLJLjtuRpMpdqP/352grad0T7usQy5PCWf/cD4tbbDmIDare8R7a1Ab+8h7MXR+tU0ZYv7eDLA92aLHc=,iv:+CMC+/7sFOjU6AcOfQXHQsNbyTDU3bUFrFkHALyR5dc=,tag:YHboCd7xSWTzoyF8C+Kdjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
