apiVersion: v1
kind: Secret
metadata:
    name: pyroscope-secret
    namespace: oe-pyroscope
type: Opaque
data:
    AZURE_ACCOUNT_KEY: ENC[AES256_GCM,data:D0yFcrlFOvmZ+GTQTfpDMicDoN9NH4TxdFNUX92gC9B+5tIE3aX269MFxXH8Cc1cxWlcBif9O6Cig60TTWk7alIlkW97QoRCSXA97QwPp2ToZVCXbn0AthiP/PMI1j/Ok6YIgT3qSoWawEyrlxKW/5o4iiFwnPHm,iv:kY04JTSVNOakykCae+Py2i7TMNIWmeidFDOG6uyxKPM=,tag:dRgYX9ep2DIC8Kg581a+OA==,type:str]
    AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:ZHpqin8D9+Yh5MrAhK6iHG4eqj8=,iv:XnAn8M3HFB6P8TaBege/jJmFr9hk6vX6VDAIPHTYpFU=,tag:4xDSaywuTEa8VwymN5igMQ==,type:str]
    AZURE_CONTAINER_NAME: ENC[AES256_GCM,data:sfxjndy0dC5e7vmX0WfpXIIAmg5cEysdZcuSZ/4ImY1rIn5G3YbDv4gBpT0/oZpES0kEag==,iv:AVHpdHNfj9WPCr8/1b1P5Zi9ziN0ic9cgEyM6I5XC+8=,tag:9p3LsCUDCFpyiXpwwJ+JOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2025-06-23T13:54:47Z"
          enc: D77tusNBcxJr5u3hiaCBJ1r-trZ5eJtypzcYn3HgzXsWKxA_N_itw8e-TJfL9Lv_dpTmwuyKnVzvNVFErgWg3DrUvb-NKIG7U-GmKPvatp-IO7hQf8hAMeO2MIAW4DpD8d44r34g-RpYtekkqSHTPURrhnTQwYV2y75K3ZVR3tWw7rgo6KdDzCD4x7_JyaO-Vwx5uGWXAfWANswXl5zPMp6BWHpGFNLoBsxVITeThO1nd8kFx96IPnptFjJkWMRA_C33jtxtjLxE9UV4pNDELVzOG-XreOP7y4LejIQmJcJ16YR-59bDN_5iA_2thU0H4uaXtHj65ds4Jnl2tDtlx1c2d6SFCiOvinp3O2YHzdxB_smWywc1qywCQYV8ELbpwpkL6Ndvzc29ifkhQweHdcYJm5Fo9CtxODhGzJ-K3al9vcKCHK_fM_92-Ut3-MasQQPR-FHJ16uyhAkoYRCzuvMx9c5DXstrr84Lm648z-WgN22PKn5Z3IPzWzoACU8BDU6xTvdet2nz-xS3vYRd0m1ZkjMXDrn5oRmbXnmiNdq-YvJfoFLSJxBWRYanbxLY6DECuMqlu3plYfamXiJKWs0_ijJcYfYVWI02eXantfG1MLReh3FpeePKXsTsEG69FgDbDJx4I7BLxiHJyjdOnDhjw0CgJ997tPmKZWgsNFg
    hc_vault: []
    age: []
    lastmodified: "2025-06-23T13:54:48Z"
    mac: ENC[AES256_GCM,data:E0X1PSuiSgjRrT8q0KTfvPCKKhGY9SwMTWkglK5zqLl2t+FlKah3hYFw6fyzdczohs422aspvJ6CO0lBkzC8alQLSFXr1Bf1f95+SGGD8Iudep47erOI8aerkoCldqC3dEGBv3tYtl3AZhYVr+5T4lgoJb81AiiRWUUdQ2AIR6k=,iv:ltm+lGZZ1+8GH31bVyDR4hcOUhV9HdlWA2fB2YY0Ek4=,tag:eDtX4mo+MxgkrxaIyy8ttg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
