apiVersion: v1
kind: Secret
metadata:
    name: tempo-secret
    namespace: oe-tempo
type: Opaque
data:
    AZURE_ACCOUNT_KEY: ENC[AES256_GCM,data:vFXWseOyC4NeWiHOx5+3oDzOpH+te99KiEaRPVrlHMy+JrppeVHK6lmOysmlyT0EIpDwJp53V26aFQAhiU/ZWqh3wq2qBoY5+lhgs+UfW+s4SXabOdVefOzU2C4YlnkQLV8Nva/hQVeMVnu3nO5hk1FsVKwBW9Gk,iv:nsvHBdyjbURA+QEm5DpxifXt3JkuRvP+8TqIjCI5icw=,tag:OhV+w4V4KtoagT0gsqeikg==,type:str]
    AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:uJ0tLxZHVtPiARb4W60SxNscKajzMzqT,iv:VrR4DCYxUAZL/4T/nFIWI4sxrj6ofbjm6zM4h3tz3So=,tag:BptIPeQ6QZRzEeR9nHDSoA==,type:str]
    AZURE_CONTAINER_NAME: ENC[AES256_GCM,data:hh08QLxykj+rd6YABagBeIcRE6m1uPzcM/46EUFCzLGMZ84OXwmCrsK3pNrPFKUB,iv:QyGGiYNiusPv1paqx2TBCasMvkhexXiRX034xx0woWU=,tag:Q7nq3LpAf7VGEv67a33tww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2024-04-08T13:27:26Z"
          enc: patfiM7JEr3WC3O9zgxqUcccUE7-CcZ0jYjSW8MWgX9qt3dQaQGK9uF5_6c-MDu72uzFpr-rAXtiBpY2jpski5Sf-FAkUGJb6aJa2znedMQJ1vwLQNbeaEQSVC4dAjTtqU9Hcnn7FAgd3DYxPty-V6rzKPjROR_K5MRQMtyTDDodz-DBJRaNtcfkx4TwwZmRZuHMqDSxSkxKj1CnunkoiPqTWVhWWZ0J3ESQT-jBwS-UWXim1GAhiDWtDIlt28iDerqfLLP-W5WrHvqnuivCnFsDkQ6Jhkcizl5LL3teak0T1X_LCvAj8FeTTiTaRJ3Ud2F_X0WtKo_08UaAGfL8MCkMbgYwY72zNISZA7ipTcDPuBIV4qsreclilCuWWasPqHvmXQRuNIhRNM4AniCrOQHGjB9r-lyzTaHU1dBlcAH0hG7H0UWRJqFTHWuZnM0-8q7JTSw5J5aE0amhsId8VBiq55BwYGuI8w_pPCpA39hb7hRDZUR8PACue8Qvt-4U_VTyjujDKS-VU7AU8g2kMeVI9JPQgA9N-RyhcklYRws6fLpmQsvTLPoK27ni9eSOd4JgE43LymHBBuXBRfuh41HGSCtTSh8C8Et0fnI_ednqP2xSKlcdrGs9Oriivqjd4kjMFbUXE9JAaEQezSC4oRa1165gA8OraX-aTQtgRN0
    hc_vault: []
    age: []
    lastmodified: "2024-04-08T13:27:27Z"
    mac: ENC[AES256_GCM,data:brow9V4Eyh9bRLBV+0mAdAnl58Kw+A/pPQyxI/5porew6LYeY3Zf8KUwQTX+qi+kZMw9EwDSxWC/elUTb4p54l0eFXqIhTWAcDYGcBqFQbk76F+YeJyLqucVhg9aIv98iK60OVurmFwwLfotYf0ST5AeSv+w/U9qfHcDkyNxhrY=,iv:8lfiSWqfZyyXxS7+O/oOu0jRdB8RMEeB+N9k9Zuvb/I=,tag:Kigr2cXhVkOkmTu4SMAYpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3