---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oe-loki
resources:
  - namespace.yaml
  - helm-repo.yaml
  - helm-release.yaml

configMapGenerator:
  - name: helm-values-loki-stack-base
    files:
    - values.yaml
    options:
      disableNameSuffixHash: true