{
 "title": "US West Scale Unit",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "SU Locale",
    "query": "label_values(kube_node_labels, location)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{job=\"node-exporter\",location=\"$location\"}, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load15{location=\"westus2\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "\n## Production Clusters\n---\n"
   }
  },
  {
   "title": "Production",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"westus2\", cluster=\"sl-aksm-wus2-01\"}) / sum(kube_node_info{location=\"westus2\", cluster=\"sl-aksm-wus2-01\"})"
    }
   ]
  },
  {
   "title": "Production",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"westus2\", cluster=\"sl-aksd-wus2-01\"}) / sum(kube_node_info{location=\"westus2\", cluster=\"sl-aksd-wus2-01\"})"
    }
   ]
  },
  {
   "title": "Production",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"westus2\", cluster=\"wus2-e1-aks-01\"}) / sum(kube_node_info{location=\"westus2\", cluster=\"wus2-e1-aks-01\"})"
    }
   ]
  },
  {
   "title": "Production",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"westus2\", cluster_name=~\".*-p-.*\"}) / sum(ece_deployment_status_elasticsearch_health{location=\"westus2\", cluster_name=~\".*-p-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Production",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(redis_exporter_build_info{tenant=~\".*-p-.*\"}) / sum(redis_up{tenant=~\".*-p-.*\"})"
    }
   ]
  },
  {
   "title": "VM's Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", location=\"westus2\", cluster=\"sl-aksm-wus2-01\"} == 0)"
    }
   ]
  },
  {
   "title": "VM's Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", location=\"westus2\", cluster=\"sl-aksm-wus2-01\"} == 0)"
    }
   ]
  },
  {
   "title": "VM's Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", location=\"westus2\", cluster=\"wus2-e1-aks-01\"} == 0)"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"westus2\", cluster_name=~\".*-p-.*\"})"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(redis_up{tenant=~\".*-p-.*\"})"
    }
   ]
  },
  {
   "title": "Production",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"westus2\", cluster=\"sl-aksp-wus2-01\"}) / sum(kube_node_info{location=\"westus2\", cluster=\"sl-aksp-wus2-01\"})"
    }
   ]
  },
  {
   "title": "VM's Down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", location=\"westus2\", cluster=\"sl-aksp-wus2-01\"} == 0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "\n## Non-Production Clusters\n---\n"
   }
  },
  {
   "title": "Internal",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"westus2\", cluster_name=~\".*-(q|d)-.*\"}) / sum(ece_deployment_status_elasticsearch_health{location=\"westus2\", cluster_name=~\".*-(q|d)-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Internal",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(redis_exporter_build_info{tenant=~\".*-(q|d)-.*\"}) / sum(redis_up{tenant=~\".*-(q|d)-.*\"})"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"westus2\", cluster_name=~\".*-(q|d)-.*\"})"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 34 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(redis_up{tenant=~\".*-(q|d)-.*\"})"
    }
   ]
  }
 ]
}