---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: cloudflare-exporter
    release: kube-prometheus-stack
  name: cloudflare-exporter
  namespace: oe-cloudflare-exporter
spec:
  endpoints:
    - interval: 30s
      port: http
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-exporter
