{
 "title": "East Australia Scale Unit",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "SU Locale",
    "query": "label_values(kube_node_labels, location)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{job=\"node-exporter\",location=\"$location\"}, cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load15{location=\"$location\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "content": "\n## Production Clusters\n---\n"
  },
  {
   "title": "Production",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"australiaeast\", cluster=\"sl-aksm-aue-02\"}) / sum(kube_node_info{location=\"australiaeast\", cluster=\"sl-aksm-aue-02\"})"
    }
   ]
  },
  {
   "title": "Production",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"australiaeast\", cluster=\"sl-aksd-aue-01\"}) / sum(kube_node_info{location=\"australiaeast\", cluster=\"sl-aksd-aue-01\"})"
    }
   ]
  },
  {
   "title": "Production ECE",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"australiaeast\", cluster_name=~\".*-p-.*\"}) / sum(ece_deployment_status_elasticsearch_health{location=\"australiaeast\", cluster_name=~\".*-p-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Machines Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", location=\"australiaeast\", cluster=\"sl-aksm-aue-02\"} == 0)"
    }
   ]
  },
  {
   "title": "Machines Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", location=\"australiaeast\", cluster=\"sl-aksd-aue-01\"} == 0)"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"australiaeast\", cluster_name=~\".*-p-.*\"})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "content": "\n## Non-Production Clusters\n---\n"
  },
  {
   "title": "Internal",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"australiaeast\", cluster_name=~\".*-(q|d)-.*\"}) / sum(ece_deployment_status_elasticsearch_health{location=\"australiaeast\", cluster_name=~\".*-(q|d)-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"australiaeast\", cluster_name=~\".*-(q|d)-.*\"})"
    }
   ]
  }
 ]
}