---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-blackbox-exporter
  namespace: oe-prometheus-blackbox-exporter
spec:
  interval: 1h0m0s
  url: https://prometheus-community.github.io/helm-charts