apiVersion: v1
kind: Secret
metadata:
    name: loki-secret
    namespace: oe-loki
type: Opaque
data:
    AZURE_ACCOUNT_KEY: ENC[AES256_GCM,data:PCqk5j6z0dN6+Uxlzc5UJARpeuKDoyD335On8FCxKGU8qojLvpfRFuaPggcbKtF1U+cNyyh9ILAmYJwOb3CLY1n4nGnd0r/BmyhzDuL7d2ka2KV3SQdcU3QdZUUvfqQjO0iVfRodVsjVmuyKCBMVtC8gOLIJ+bZm,iv:BOzrwRLAsr50w0RQtsSfjiLWVN9at89Gsa+qNZJRYY8=,tag:pU3VrdOMUo44HWtf3AIRfQ==,type:str]
    AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:TS/zCujnQ32aSx8ACPQZ4Pc5sFc=,iv:OjdBOGXGXpQyFwsTeVwADVEdOO9CQkXYYpl2hJFpNao=,tag:IYAo+skg8ADC73KoTKcpOA==,type:str]
    AZURE_CONTAINER_NAME: ENC[AES256_GCM,data:i/6rnWy+miCcRj07JZIPe6zFSG6QS/Tt2EIAu7VbyLc5hCUy1JHBb+hy7VA=,iv:u9qVQ8wxfcILAatQUeIn9drz+FYChYLIEPB1PvnVOyo=,tag:XYapnxub6rPOR26DKKpWCw==,type:str]
    .htpasswd: ENC[AES256_GCM,data:aIXP74yrrLQP+0OXBSHn6YD+OpfazViqpZyMNrY+tc3+gDWd94jHKRvA1jT2afUmZap5xjM6NIdeMbFgmGsmRg==,iv:qR+OcOy9STIcpaUZn+29N5+oxoIvVG4MPO2iq8+w+H8=,tag:2swj4UOFJCf4e27F6c7guQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2024-10-29T09:47:10Z"
          enc: TIbeuymjMcDjzZ9esra7s3NVXdheoTwmkoVy46eiTKXDPYT2VHYI4neFwYo96O3rf2zwgvd8c2TMxSsPqAJzvKp7a1MqSPkBiPRTZVflApcJOEwOoj-hJIsv_YzrVQH8CwREEPyrX5vLx-4WaZgSBQS-72GKhPlelqjos7ccMrcGUXPLeF52OAAo5fTArK77tdO4w3w2KmYVc4JZuT1J0EkzWxPpLuqHrfymczA2dG1nsTUYoqBZQc-gVi_8mnHX3TiFJhW3eJu5snA5QCbBMlrq-VnPI75Wy13g257w9sGnrBTJNH96uO8yPpJK-unClpyStHHPEgWxCgp4llbapQ4wCcusPMz0Q5u0_OpkfVlrG_PX3DGg8fQWFSIZeUPwNSFRukNjOWW5JAefkZALi_i5bv3rTTDkH7C58bET86nn9M0Q6mzcMShWpN0WEq7lOiEMXWRUw8DP9FUYHt24K65zERg4Q74cw_6ryqTV_VoKXrXLoG_82NF1LR1ovSDJroca4fqVRlICt1qkg9a5ZCdsw-S55l6I1ua-I3crzFDAWodutZjktUFFa7Ga4C9NTazdW17DvlowVT1QZ8UIbjkjNaPdBBIsxp3y7uHOYiTnadoB9qr_NHdOORQ1GgdUg24NFKMc7rcD9I4PAaU4Py3-dOeCurzzZ8iLfA7iuCU
    hc_vault: []
    age: []
    lastmodified: "2024-10-29T09:47:12Z"
    mac: ENC[AES256_GCM,data:8uUj8U6pcsaaA8F7MY0LGPAemIS0ogtqxU1sTlUwdg7bsCtwBx7AScXRHjEeAD1p0rFaYMuPJxWMREBTfPnGiO37us5mW2iYD+5EoNMTGUJrfj2dwr1u0mdYckW5XXoG/iL37cTdsmebT4QyIDJSkAR99mqeZT1QmpDJKqpuP5A=,iv:g6aDlmoK44vMj8p45JV1lWwoyhmhg12Hj02b7hjuW2k=,tag:1k+isR2SLGjXFM8P9ww+gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
