{
 "title": "West Europe Scale Unit",
 "tags": [ "Scale Unit" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "SU Locale",
    "query": {
     "query": "label_values(kube_node_labels, location)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"node-exporter\",location=\"$location\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load15{location=\"$location\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "\n## Production Clusters\n---\n"
   }
  },
  {
   "title": "Production",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"westeurope\", cluster=\"sli-aksd-weu-03\"}) / sum(kube_node_info{location=\"westeurope\", cluster=\"sli-aksd-weu-03\"})"
    }
   ]
  },
  {
   "title": "Production",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{location=\"westeurope\", cluster=\"sl-ckeditor\"}) / count(node_boot_time_seconds{location=\"westeurope\", cluster=\"sl-ckeditor\"})"
    }
   ]
  },
  {
   "title": "Machines Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", location=\"westeurope\", cluster=\"sli-aksd-weu-03\"} == 0)"
    }
   ]
  },
  {
   "title": "Machines Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"prometheus\", location=\"westeurope\", cluster=\"sl-ckeditor\"} == 0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "options": {
    "content": "\n## Non-Production Clusters\n---\n"
   }
  },
  {
   "title": "Internal",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{location=\"westeurope\", cluster=\"sli-ckeditor\"}) / count(node_boot_time_seconds{location=\"westeurope\", cluster=\"sli-ckeditor\"})"
    }
   ]
  },
  {
   "title": "Internal",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"westeurope\", cluster_name=~\".*-(q|d)-.*\"}) / sum(ece_deployment_status_elasticsearch_health{location=\"westeurope\", cluster_name=~\".*-(q|d)-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Machines Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"prometheus\", location=\"westeurope\", cluster=\"sli-ckeditor\"} == 0)"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"westeurope\", cluster_name=~\".*-(q|d)-.*\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 }, "options": { "content": "\n## Internal Services\n---\n" } },
  {
   "title": "Production",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bamboo_lifecycle_state_gauge" }
   ]
  },
  {
   "title": "Machines Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", location=\"westeurope\", cluster=\"sl-aksb-weu-01\"} == 0)"
    }
   ]
  },
  {
   "title": "Active Agents",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bamboo_active_agents_gauge" }
   ]
  }
 ]
}