apiVersion: v1
kind: Secret
metadata:
    name: use-e1-contenthub-aks-01-objstore-config-thanos
type: Opaque
data:
    objstore.yml: ENC[AES256_GCM,data:wMTZDW90njV0Z8pzxFSMNs9I1Si73iMIPbeJyNYrfErytECJiWnZGqys+zQxdXMVklrO8kQBxgi1Dht5fA8XTZkwsOcF3S79yOkogQefSsfLhr20AcGvsV8CDY+XwoXN0Sbx+qvAsMz+933r0/fFszwO6CiuNQD4l3lWI/KoqMT3t5yuXEEbpE1ybFy2xWVUkDzM9YRrPiLaNuvRrjDhzrC20yYIwfWmlfth4Ql7tHw9W8h5Rhzc9g23oDLlpO6W4Vq9bREXWJ6JgmL1JGhXCqIjaWvGIU5aTn2EOroDQmlqhzTldRe+OyKhbQEB8vPdvniHndtctgqRNTSHS6bUfmooQ1ZBQKgnMqIVRdVh6fZEBrarosKg8BKTy0Ynx1ZSRiZqeWxPAtxuoJzk2Lvof485+DMP7kLpUnWfuAfcsYOF/LEJTTAgiUEs7JWZoGhbrwdwJw==,iv:tTx/7h56mzFgF+CfY8zEArlfhVUIsuVL3Nx923UL2NU=,tag:60Yzv/ojWQ7Ft+qicMkrbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2024-02-15T08:19:35Z"
          enc: I9pKnMbakY68DM7BYnFZYVb46fp0CLSl0eEqBpYTOZfyNCDE--1DyKMfDENvpgKvEyUK2wo8YDlHhJ-WVdKU3gi6YlRXwDFYZWHyRq2iRcw6KTgFhBtYioYJY-YSIeUeAQE29YvID-K6iMCX-yoSTJwPxs86bYSo0oif1wQwXtsuhh1TvC373YTf7N532nRbGuNgjQwcU-BszdMiH-_5HNdZl4FE8Nv04GfljNN9LcMOwkvqLo-jmt9E5hS-dR9ySrglcHsH62Y7r1xgFnrnMKdLTO7WqKLeB-TBBfwrtduxYDeHRcV24132tIomktz76KppM6P2LBPTYKWbZOkWieBcap2OHQ5puRYyQ7Kz_HhD9-lkAq6K0dJiXAdxv0rgBVJwCvci5E12ZBW2z80nR-h8PM368t2VdrdzvZ1xd1BYh1JnOrfZq8MjUw4YQmE0trzs09VVroQbqeyBZi2PHcvl0XLWpkZI7f8wOh63qmBHsWKLQJzOqfiJcJq9_ImuCZohxe3_NC2QQlgLAVYB1cb3UNvcMbJ7J-hDPUFpqYAOsgOD0lLhFNChA8VnwzLWjbK715hyYUWHGyIsKDOk27boR4XYSFiNbVa8xtE2esBqNC6bRockksIaRNtnWUwjhHBYqaFbTClu5uOMQ7TOA_ndgRnvoJs0zqpYASwegNs
    hc_vault: []
    age: []
    lastmodified: "2024-02-15T08:19:37Z"
    mac: ENC[AES256_GCM,data:J1cPE+xvgRUM4fg5OdRwLeBSfI/UCotVWe4hmZzSY2IE111B1FVGurw0/KfbCcEQAMFCLtqYJviDibbla7ZPgKEqAZEoO+FgZF7gxdsFo0mkA7S2FygFPIsafVoIhjZwRHleMIcs72omZX4EudzYyJQl6ZOhcEGLn8rXNXZXLbE=,iv:Ld/eBiYZommtfXe+Qmdu7Dr8FfHRCvY1Nohue947TDA=,tag:gXDhMLjQR9Sd0mdkSL5J6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
