{
 "title": "Global Health",
 "tags": [ "Global" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "SU Locale",
    "query": {
     "query": "label_values(kube_node_labels, location)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", cluster!=\"sl-aksw-weu-01\", node!~\".*win.*\"}) by (location) / sum(kube_node_info{cluster!=\"sl-aksw-weu-01\", cluster!=\"sli-akso-weu-01\", cluster!=\"sli-akso-eus-01\", os_image!~\".*Win.*\"}) by (location)",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "\n# Global Scale Unit Health\n\n---\n\n\n"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 0, "y": 20 }, "options": { "content": "## Europe\n---" } },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 8, "y": 20 }, "options": { "content": "## Australia & East Asia\n---" } },
  { "type": "text", "gridPos": { "h": 2, "w": 8, "x": 16, "y": 20 }, "options": { "content": "## United States\n---" } },
  {
   "title": "Western Europe",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"westeurope\", cluster!=\"sl-aksw-weu-01\", cluster!=\"sli-akso-weu-01\", node!~\".*win.*\"}) / (sum(kube_node_info{location=\"westeurope\", cluster!=\"sl-aksw-weu-01\", cluster!=\"sli-akso-weu-01\", os_image!~\".*Win.*\"}) / 2)"
    }
   ]
  },
  {
   "title": "Eastern Australia",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"australiaeast\", node!~\".*win.*\"}) / sum(kube_node_info{location=\"australiaeast\", os_image!~\".*Win.*\"})"
    }
   ]
  },
  {
   "title": "Eastern Japan",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"japaneast\", node!~\".*win.*\"}) / sum(kube_node_info{location=\"japaneast\", os_image!~\".*Win.*\"})"
    }
   ]
  },
  {
   "title": "Eastern United States",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"eastus\", cluster!=\"sli-akso-eus-01\", node!~\".*win.*\"}) / (sum(kube_node_info{location=\"eastus\", cluster!=\"sli-akso-eus-01\", os_image!~\".*Win.*\"}) / 2)"
    }
   ]
  },
  {
   "title": "Western United States 2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"westus2\", node!~\".*win.*\"}) / sum(kube_node_info{location=\"westus2\", os_image!~\".*Win.*\"})"
    }
   ]
  }
 ]
}