apiVersion: v1
kind: Secret
metadata:
    name: tempo-secret
    namespace: oe-tempo
type: Opaque
data:
    AZURE_ACCOUNT_KEY: ENC[AES256_GCM,data:hXm34yHOW4VOudCtLxjUNrwOVXtC1zQ1wyHVOJsFPfu14qhrJzkVFLOmz//Gp1CQof/orm2WnjZ2KumAhrBxMU9NijjO3KuPdninfWb1/r0FqE0Tt4FCfPYafoAypFQYYLdRuLVRwauuThJXvfriBvOM44JgVyrL,iv:haDyCOYHQtWoef3ZU7fI/iW+DY5skxg5ClpGObTLjcA=,tag:1tpVVTID5/HcgqduIRZ4jw==,type:str]
    AZURE_ACCOUNT_NAME: ENC[AES256_GCM,data:Dx+KB39hzSv02OmsWLPoVg==,iv:1hVYbxf/GRtRQ83MwlL8yUq9BlfzKb1/2HrDgcgK8o0=,tag:Khy1mw/iv7njvsncWYPgTg==,type:str]
    AZURE_CONTAINER_NAME: ENC[AES256_GCM,data:Wf8IMU5oxewFkER0QGi/Me2RbjHMlqiR/N7h7w6XEjGer4sFsC1MikV3b2g=,iv:qXJN+LG0WN2k1AqK14HjntpHPO1Z6mM4JI0jEWAChOc=,tag:BLskCepXhZNWpoJfzTpg8g==,type:str]
    .htpasswd: ENC[AES256_GCM,data:L25hX37cry8vMKfyJ56I+6I/K+vBTwEGv8vFreJVGxHNuBkLCuV99D59zcuSwbB1f9fp7saR2Es0cj29vtj8lQ==,iv:96Q9Y+yAElPHWFdkka/7RR1qKOTGZdhiU4AtRA/BeW8=,tag:LztmYLK1W2+GYywzRRwLgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2025-05-30T04:18:13Z"
          enc: F0Qer6Kes_oSMC05pwq6284v5XYzt56viwKa51eE-Y7ZJIXvqVtfdPxizo0qBdZJseLNJSjI7X3Xlq-Wh_X-daEddtpeR8O3R3t5GdRDgFdi2gqLUoACIENI7MqHpG-ZIC6G_Y4VNTk2ZEc_KFt1WVT4eoX0atp_PtMumHeg_mEtMeDXPUR_hcqYEmaXRVdF5E96qavpdBa2Fi3Z--45Qp60IBxCbjKZuEOy8N7ikPpiD2soncoLYHArnrzIc3SmRuLsIQurpbEpLSaVaKLFeSwzQtkEedZlbvTN-VMv9cVUC_gTE7Z7uLGT9pgz1qVbHI-7petXjBvmAZbsSjuBFMZ_95BNoWyvJRBpnwAfPJPoI9uQAJ7ZOlsshPhEfpNpAo-0UJPkOBJ118L4bRKxJjcksFX39riRo-itYQDq4XjQWnyfh1vfYJfkr6XGTh_IFLM1Oy8B85bXa3AjlmiMR3UJQjtrFrCFB3ZBLvtU_2MJ0_V9VoSXohkTB-TAGYWFXZTUKkiyTW_FCkKV2G1j9hMu7Go4PXJfqq6hcbyY0oFg4VJBULIdjMtozEvM5LcYVxec23n2EIhWFQcjM_GZdXCxTQ-dFr7lCHCJQFZf59C6iGMMRnuRWjIprWsVyX40Em7GUnTiDLMEbKqlot7iUGPGL6EsHUUIu9shZN0Cbfg
    hc_vault: []
    age: []
    lastmodified: "2025-05-30T04:18:14Z"
    mac: ENC[AES256_GCM,data:Fg7LAZXasB8+KYzXxrPY8KVLgbdvf8sxK2O+mpIQN/m99C2U6q0K4zJh3bXYLqWV78KABtmtBwxB06GhzRgsxoL+sOjfetFXdJ1ckuvc50JB5LBP1tE+n/UN1+kKj/IbU5C2HtMEVFkII3RfUMDplv0ihFKATdjwuX9tUwqyWug=,iv:tH6KoLpwbZB359P9zeiPLfexxazT5wO83ttJP0fh0no=,tag:NJvJPdMF+akGLVYaK0pg8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
