apiVersion: v1
kind: Secret
metadata:
    name: use-e1-cs-aks-01-objstore-config-thanos
type: Opaque
data:
    objstore.yml: ENC[AES256_GCM,data:E08ajQvtbefUBWKW/5XQyaJfjhLI1LpcYIR1VrOnCn0/DohK1A1qhMnj30HYjC1qshcTt2z19q1F4nOXRpCKQmacPK0PkleH5rSUwuZaa7q2MreY55T12CjVa1B/+9iZOo6dtCbKt+G77C1ivEBV4fQotvxc0OTkEUCnCRMHKb5IVu1CJpDslV0gHC2xcdd2ASkjPPC2UKKXU3uDKy8Iv5L6RmiX9+lx6o9QdkupUVqsUZSjVNP5hnCO6wTd3g62eyUPZJEtTM7vSKRfFGeD6SaqFQfo2H5B9DchBrNciGQuwjGRYcOHaRYnBCnEUzxPkws8G6a4QJr5t4QuSqJxlLBnBIU3p1D0bqU5cbyt41yw3JSUYo8ZOQ17+E3qNosaNYO44VmpN1r6quY8vni2ZQ==,iv:rvoo6cDuz6f3UmsF6htnKRGfE5BeXZK9ShZKV7qO2MI=,tag:XhDR4qG45oqsJQVgQHULkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2025-04-24T08:01:52Z"
          enc: FOPLT-A860q5XsqWAb4yUD5rMQ_uj4Yg8E7x1DTAPJR8TTfsXQ5dWeLHu3n-V5Tn-JRCkD2niZRTRNTjlBSS8PXxxv0-Fhqcnd82_xad8SMRO2RjwNo8iQJqb7srH1_re-neDufT10K0bQbJaXQU-Aru6sfv5Rsdka-qNgCN249_6A72JjLYV3x-AlGHu32Db-qi7gy3KFgO04JDjCoAtgPFOXwz0grS7PiX9kl-Rd2pQz_82ZDmscUfHCGsosjZQAMmr6GTuAqA_0oE3sdpWOS8Eqz9L9Z5IGEvp2ZUNWvbLnmxaPpL7eLYvG5SuUHQUk_SjDhN4lKRAyiSrGLB8HuItOOjRWDsqT9xPwae_vL3OTdhEf8DjZtg_8fZSrC6jvrBMeJW8p9cqASY5Drru9m79BNF2QoDiJMxdLRXByu_VB_UKpLDh03XfxkAhTZBVGR_chhsd-1jtTB7HLqquAeQQKx3VnDE04K04-ZJhLCqrhwd0gI__TppANK8RIYuzXctzLDsCCy-KEibhcXAlCCkuHe01oQydTOFfcIj8xyCbgQ4UWDqVhFK2hWjJKimbxoJh04bUwa5B6WZYrwtg9lD3A_zoAIc3BE7lWGzrrAoJovDf5HMhivVT-nlQCBfDkodKsP8tMEsWYd4e04H7eC_Tl87XXK0pHJNYDisxIk
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T08:01:53Z"
    mac: ENC[AES256_GCM,data:DSf9rnPGFy6GszGuQPmbVWTzqwEt1O32tTKTW1LIKRwN1RA5/2CHT6zkvJ5cOp2EMTDqjiHgVlEFL/05Ve++RXA1eGVwLOE6U/O9iP/x2cQdsMR1gPSCqN5UPm585KRwD8TKAywBzFOyOonKq3RkgrmqGZTQ5gJXFHmYwI3IX+k=,iv:uTb55lHaeetqMZJhkD49kPufclfIxrRLrzX7yFDBPng=,tag:S0MtvMwRj4wkJ+HnOWexgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
