---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - namespace.yaml
  - helm-repo.yaml
  - helm-release.yaml
  - endpoints.yaml

configMapGenerator:
  - name: helm-values-alloy-exporter
    namespace: oe-alloy-exporter
    files:
    - values.yaml
    options:
      disableNameSuffixHash: true

secretGenerator:
  - name: alloy-exporter
    namespace: oe-alloy-exporter
    literals:
      - jpe_hub_conn_string=changeme
      - euw_hub_conn_string=changeme
      - es_username=changeme
      - es_password=changeme
    options:
      disableNameSuffixHash: true

patchesStrategicMerge:
- secret.yaml
