kind: Secret
metadata:
    name: alloy-exporter
    namespace: oe-alloy-exporter
type: Opaque
apiVersion: v1
data:
    jpe_hub_conn_string: ENC[AES256_GCM,data:6GvsPsK9OK4K/eS6MBVpbnOoIeW3eNFt8E615x49MTu0I1z6+7KpEhdIpwuIIpS7bxZ+49fKhnaV2ljQ7DfuHkPpCdNMy0Xwmi6KuAP2EObdgvFgLRyI58ZRubafD+pPz1hERcxvdenie4+DNxTPojV96ZQw7AH0jtGvPLC0Eh/5Xy6LQZJE5Z33vVo0WS8YNiaSS3dR9K15KzCO1SrjdqkAgnUOnrLahQZSAWhiNUqOTfNz/YMVWHhBBDjgtTX5Nk6liBHI+bTo1uD4qo19zL9YTM670rUd5Xgji/IyDxfsugjHJdKKDTdButfLQJfyxGbhFWIdxXYdzu+6HH9R0QjOLPVEYnUl,iv:bhIC3qGeKd8dEN5ubp4J5OqjF07Y1Crh0RmRO8bDQMU=,tag:3CUSoo0UXRKG1/eBNAXiaw==,type:str]
    euw_hub_conn_string: ENC[AES256_GCM,data:TpZ2k8vGyh1aXfcgK+oP70Jc3iDmnY094M6zxJerTeoHnlk6gdtOxeM/FviZJZ+C9eoSuHZGHUSmaEaczyH40y0PTB5HBydJwvB+cCuOSxvV0a6VgxjMbexab6OxB9waG2n0+NLElWBdlB4EWazKT8FFYf/H/t8gLcJoF6wEp7Vvk6pSPUslDL6u+pccd3yycAJ4lcCfO8AOGNy4Qk1H3ytLxgevfKTPX3/87FOEEPjTKxFCdNou/FfE/9l1f1kdrCzgH2XmC0eVTU/nqMf4CwL0mAtBKAiyok40C23JfQF+8AkFfTsV6eTbyMh57VGhhYRaogcttzviKgNWAk4JqvktpFEXbpKM,iv:FfZTLwnQdbt0cxRoLByXln4KZkQbvECeeXQjxJ45hZ0=,tag:2RAYpkCFALY9B7HzHv+QYw==,type:str]
    es_username: ENC[AES256_GCM,data:8+hHbC4rt04=,iv:0ktPLN1xvuJBfaYT5X4b3uyL8MLvYogEqLnkwI/zTMM=,tag:3WtinRQXcUrBoRYVajGArA==,type:str]
    es_password: ENC[AES256_GCM,data:C2LFS8o1g+Vcy1GDesUtAeyOlywI/WVk8dKONfSDreUUrFCZ2eRPdyGaQf0=,iv:Qnpf/80096VdgEyBpeXYWZokAMMNI1A2kFrCIo6sduU=,tag:uYR+rMMTtb/YyAIcOG/gBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2025-08-08T08:36:24Z"
          enc: HEknPu0WK1S1MDXHE1UGKknaYz-HFhO7nL91rRD42kw39IMaLxTCjcAsDWvhfbM-Jqm2Ir5HI8NnHNIgtVz9Jo87-msFjJtiUIqqXc7CcTxwv29pegj3_Mbm5WOnQucQE0KH-VE-dYyc3eU_TffkXzNDeHh-BEmkhPYVExoWNkSSCk1OiRM-PsLC7NYQ3DKQBs2yIz49BR5bGLclVEzOpk6w9ra-QrDZiIRP5pBqUb5WEZx4yHzMG21IxFnKmdAhnKQZCmjwQoAqEShypcORGoR1Is4KaGUDb0fjydWx07nmhMC6xO3e5Qy9G1H0v2ya6toz61LHZCcc7u_0trlPvDDeKwrAxXH1LtbwOM6ZCWp9CwRsEXYZa45o2125KqcbVlQIBRhVg7zvrobO170LO5ElOhVTgfABVg3xaTLSdXftaPD9iDg0GjCNGSubr4i3yNZuQezD1muTsurNLk7IGaVNxGUOlYdyun84qt6afKH2rwp3rvF8HUmrF9bq7nQyD7sEufieplbwpj6GSQ8reM9CP_xb0Hv3RQE4iVYky5wVBiz6x-iZsv8Ayn74OXRZJkZtXfPD6BqCK-jgNp_jrgmJsvUF5TemlR45xB2BYKwQUFR4ylgiq0PmJQw7HANNqbYQ1dOsTVET3VU1D_UJCvEJXRUxCREbHyvs-NloceI
    hc_vault: []
    age: []
    lastmodified: "2025-08-08T08:36:27Z"
    mac: ENC[AES256_GCM,data:S484MUWu7C0O2fxZiiexa1PZafS94S3Z9D7Q1bhfs077fKe21vvvPPTNyLXmHAIb3kWKf3G840ZuiBnEcI90yPRGQs/2kQbD1DlaVOMN76AuYYANAMgiRXbGdITuz/wbidKfnbCIe38/TqMFnwxenS0PlK+jLKz/fy4cBSCW0c4=,iv:5AkA5pqaRZ8GRvcbRlGhw/LRDEScdw5hkq7RChzlT6o=,tag:jUpX3xtRlWsDUWiZKH8MNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
