apiVersion: v1
kind: Secret
metadata:
    name: eus-e1-xmcloud-cm-11-aks-objstore-config-thanos
type: Opaque
data:
    objstore.yml: ENC[AES256_GCM,data:qPPLR0bCiTaTU+0IOkyhTOxKdo+o3cipcZciytWd5GoRHcSDaYycvAdG7oc+H7HcqtYixAJCZ6PCGVNMUje69ywftRW1CfkqXtYOkwXiLgV5smAPsZwQYMP/K1Mtfl3ndmCCBzfk+xZEqtsfRemAk65m6CLPATdTEZbJ3Ou8eu6r4wlKIR5OkHCfFeHB9lAQDUVn2zroX8slSHJEcbFH5vxwf4EmXzWaswhRcYyU8vKQPQbJfCbHAktrNLpznnbxF2+qSUEExk2cK88kFcK8RcL1TfL8NCnj6XQHjsS03XMuqVTLX0arZke75LxA7v5YJzhrwfdUvBAlH0W3PhU+MYqN7CxOWnzsVt3kVHnkVFGTJfCzuIA8YOm7wDfxAtB5q6W5pM9FieSBdOCk1HYIgtpivxi+vFlqHiAUNJKQ+enesVIi,iv:kUjwAwiFls4tdNLxmVeEJr6JanRLgiCxqbHFogTNKTM=,tag:JxcqhconBSG4rkRfY6rqtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2024-08-30T10:43:38Z"
          enc: 0gcLIwo22blALUrmJhqDtB8PIlJT2WQsiHZu7LTXkciAVvlihFyYcV9NI-KTG0WoZSzMVSWQVLFmJhNFWdKIliXYNBUk83j7sJl2tSf3UyKZz5EvuxVCo4mhP6vcI9OKW7UAa651qbGjibJjMomtdwNmiiY5IYLT-E5FN4a0euYKjkoyMYWslylgt7ztHYYaw960CyUT9mDwXKF7ctD84zFM1Jy23Q3kHssT3A9gLeI56iVR7qrksPlVnHlYiYqBuDHuxOBNLhJgD3MRXujOt9rQeeim59jLffZxszR74AT-pD5bUA61wKwnCCFgHUcRph21ZHzaM7p-MgYbFZX6_s09rfxjwtbnDGV9FP3Pyi51nZpSNlVuDdYxb3O19FQfgD5uJcqmQi_V1GoK2YMCCx7OLilMgkDtxED7czExLtyr93vxDNpY1xsfS1GjxII8k3MpXtwB6X2Qt75vd31zgetju5xUjpuX7Nz8gGz0WDu6O4SG5QnCq2xc_ikxiiOT53VSXHDtgRfVJhd2lTqjDfDPu5FqgKs9CGdlXVJUufolDQaTw-SnCwoJsweh7kUqkKCulmp9CuTB-ywKyyJIT0KRAwECAGPRct0LQZUNllOHBXonDg0qjAXzFBVw8SfPBWwS0LiF6jufp1CbibacTZbJFFackdBkVWsoV3cwC2M
    hc_vault: []
    age: []
    lastmodified: "2024-08-30T10:43:39Z"
    mac: ENC[AES256_GCM,data:idrnPLkALQkJuaF0Q27QW/acc7GbhGpJWR31r0NAQOcV+VSGjx0M4G0Dr+7MZSqLGe8HaJ28uEj9ZIBM1g8Zdq5JntGBDqnv8uqBmQvjjIC9znAx3z62nmAJWKeYIgYyXv07bAcTvlACqE9zRz/tAGaDfeGceDj3LR/EiJk14Tc=,iv:nVghEgYUhUg1391OfIsJIGxAge5cZzL1SQnHpJ9cP08=,tag:BG55ddg8m/QrZReZLDP0JQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
