apiVersion: v1
data:
    s247_device_key: ENC[AES256_GCM,data:NJFgylRhugoizRwza8Ar+MoWUJsUApX8b4NWSs6nmM9wXqwStGzzLbwyokmIiuUeqcp0lmnnUQ0=,iv:7uZpKuIFJykzv1cWsjEijOIigqEmqYvojoUMNwUvRv0=,tag:3KZk1Go3oQeaMZBxpjyzcw==,type:str]
kind: Secret
metadata:
    name: site24x7-agent
    namespace: oe-site247poller
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2024-04-12T11:13:32Z"
          enc: TKUZX2_m8NYVLs5SoELpkU5Ap5YyKsyfFek0GqSqq0hwjuBqRt_LKW_9GViNI6zTWy-OuvACteLwj7IO7d08eKnz2y5rV5nE2W11SDjMm_L_VlQw4w9VUqhAqbxLLTcDgsyTBr865hfVdjYt1NrRe-w2TZHkLT1JuZ1RjGwfZ4kS0NGtNi47U5ahpWQPn5PCNttFa8l8S0p6MBLyB7WN0yhcnUsLSD-7c_vzshaoofYnTlxdS0m1wlkxEqTXOS2WBoAXiPXj05wigF6Bn9mbT6AwbN6lgbIkNcNpqoveFfX43Djp6-cRtLR5UBxrB-fn48dlyYInCqZURTN5EYNBgVxQNfYnAjtSaI7I0111BbtPd1e_rn6zHjyuNgxTfXdqcIaB_r6PAfoa0a6w9_uvm2KNR75Ki9Gkxur_U6zLizZsARe74Ad3owCDh7e4ZiQZF2RdMcuYE5B9wXfzHCQh65zjlpKBFvPQHvpvCT12vjAnW8HaRVxjjkThKuVGX_JaPsaHVIZqHvTwCe49fcddntCRiaW261XLlymNxk_oe5JMlAJpPPcpVITcioqPYTCTR9guurYmt9fPmvSS7AtRpO5FEKgxpVnryy6JLnwBrYiCj9avqPd-Vqvks8ufqKpdsbecfkVz6j4iKxk6l8uC6FIFl5vy55kMsU-xLWJszJA
    hc_vault: []
    age: []
    lastmodified: "2024-04-12T11:13:33Z"
    mac: ENC[AES256_GCM,data:S1UfGVwONwNw0Gbgrljb1Uj0Ij1cvG42VPFYWI8/8bE9uVR3JgZ71AoAJa54KPHdcvM6vHsSe/MFWoeSMk/i4XVZyfIT+Q2WkUDNkeJNow1QJayAgkkuK0E7Pny28lM7TW28jrtpTVox2/iBrLAJHBT7TUWUQWVyxCY5WlNQ7t4=,iv:ky93E3aU/kS6TYXKJZWh4ogqP/kq20l6C6eAD60kRBs=,tag:lH7wbP16c57/5V+ujoHN6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
