---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oe-kafka-lag-exporter
resources:
  - namespace.yaml
  - helm-repo.yaml
  - helm-release.yaml

configMapGenerator:
  - name: kafka-lag-exporter-values
    files:
    - values.yaml=helm-values.yaml
    options:
      disableNameSuffixHash: true