apiVersion: v1
kind: Secret
metadata:
    name: databricks-exporter-credentials
    namespace: oe-databricks-exporter
type: Opaque
data:
    DATABRICKS_API_TOKEN: ENC[AES256_GCM,data:H2Qb3YhTch8SMuuO+S80MlfI1/s6SWEPqUd8dADVebd25p6bwKNKDxx8rCJdPkLL0L4lVg==,iv:C0hOoA3wT4czOGp3FJOk95YU6z5iYCj1fGlTyWCLmqs=,tag:WctyCCWETABXWYioN8xczQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2023-06-15T13:56:40Z"
          enc: uQQG8xo6dgpwKrcUMPswnvHAxd_907Uc9ikEsHY63fB7pw6vfPatOhtHErfEYOZmzQ7w3h14mEF5-rcRvNbdkimTQj6_RIGMEArIdmOT_3_tDBuRuih0XE21yXOuQ0SzT1mSPOzrWMiC80W-AH2dMZOimrKnDQzFkx4ZZsvAvfd-_YaCsCUG5XHUEAbKVdFbFyYUiEAb7dAZI0B5dvBHvCF48BE9jUx4FGSrVq4oTFvd6mEyj8ms3AphLoLUHEYxNaDTBZwaksrTiXnrEZpADw1S_GB_mhNFTMJwaX8yv5s4vgjw7Pwvu6f-ck2vnrsoWl96b0T8tl5kmE6VukvwWNZiEn4UvKQlTpJ5xc9HS6mS-GUR2s5AyJWQfqzA-EbYb24Nq8w3fXngTX7iFoJXb5dTSWCSmB936DSXrZY4qEtV157gihXdVSGjKklxyj8JUg018TGCNAiZgb_9j8q39H6otJmtTfSlnLc1JmKUkm-zHYgWvVTtGGBPjTGeM-a6TTTBqS985DgfIeawwdwV6KJpIkKgAb2BYsKuIw0YUradDScAoeYFrmwHpil_KJN-D4s33FH6xkPzSEglK7bQx-G0n3hi9m6h-Ilek02ixjS2_5IE4Ysa7eyo-WwQt9VmlX4fGteTloEgwfQVJZV10aRbQNc5VpRzIlwoEqFrgOk
    hc_vault: []
    age: []
    lastmodified: "2023-06-15T13:56:44Z"
    mac: ENC[AES256_GCM,data:e+DK+xyWxN/RpVS/D0lY4JKc7agvJ4V8cVk68IzYmugxZIMspzHqgUNXwH52MGvI4g4/Bw2yQovXcHLlXLJb8dyoYgtZZjbmJiS+JUf2Y4LzGlwjG2pzDBMfIi4YUca8S84Tc8K/I8Yw6LTL5WAGzN8ay222HGK/aYx2eV3imWY=,iv:VhIlgnYz02tItsnzXJvjmzovjWbp7SYkPob5M39Lna8=,tag:JXSmM5IUu9tsNYqIxYlDOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
