{
 "title": "East Japan Scale Unit",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "SU Locale",
    "query": {
     "query": "label_values(kube_node_labels, location)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(up{job=\"node-exporter\",location=\"$location\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load15{location=\"japaneast\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "\n## Production Clusters\n---\n"
   }
  },
  {
   "title": "Production",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"japaneast\", cluster=\"sl-aksm-jpe-01\"}) / sum(kube_node_info{location=\"japaneast\", cluster=\"sl-aksm-jpe-01\"})"
    }
   ]
  },
  {
   "title": "Production",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"japaneast\", cluster=\"sl-aksd-jpe-01\"}) / sum(kube_node_info{location=\"japaneast\", cluster=\"sl-aksd-jpe-01\"})"
    }
   ]
  },
  {
   "title": "Production",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"japaneast\", cluster=\"sl-aksw-jpe-01\"}) / sum(kube_node_info{location=\"japaneast\", cluster=\"sl-aksw-jpe-01\"})"
    }
   ]
  },
  {
   "title": "Production ECE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"japaneast\", cluster_name=~\".*-p-.*\"}) / sum(ece_deployment_status_elasticsearch_health{location=\"japaneast\", cluster_name=~\".*-p-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Production",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_exporter_build_info{tenant=~\".*-p-.*\"}) / sum(redis_up{tenant=~\".*-p-.*\"})"
    }
   ]
  },
  {
   "title": "Machines Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", location=\"japaneast\", cluster=\"sl-aksm-jpe-01\"} == 0)"
    }
   ]
  },
  {
   "title": "Machines Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", location=\"japaneast\", cluster=\"sl-aksm-jpe-01\"} == 0)"
    }
   ]
  },
  {
   "title": "Machines Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", location=\"japaneast\", cluster=\"sl-aksw-jpe-01\"} == 0)"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"japaneast\", cluster_name=~\".*-p-.*\"})"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(redis_up{tenant=~\".*-p-.*\"})"
    }
   ]
  },
  {
   "title": "Production",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"japaneast\", cluster=\"sl-aksp-jpe-01\"}) / sum(kube_node_info{location=\"japaneast\", cluster=\"sl-aksp-jpe-01\"})"
    }
   ]
  },
  {
   "title": "Production",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"node-exporter\", location=\"japaneast\", cluster=\"jpe-e1-aks-01\"}) / sum(kube_node_info{location=\"japaneast\", cluster=\"jpe-e1-aks-01\"})"
    }
   ]
  },
  {
   "title": "Machines Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", location=\"japaneast\", cluster=\"sl-aksp-jpe-01\"} == 0)"
    }
   ]
  },
  {
   "title": "Machines Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"node-exporter\", location=\"japaneast\", cluster=\"jpe-e1-aks-01\"} == 0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "\n## Non-Production Clusters\n---\n"
   }
  },
  {
   "title": "Internal",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"japaneast\", cluster_name=~\".*-(q|d)-.*\"}) / sum(ece_deployment_status_elasticsearch_health{location=\"japaneast\", cluster_name=~\".*-(q|d)-.*\"} == 1)"
    }
   ]
  },
  {
   "title": "Internal",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_exporter_build_info{tenant=~\".*-(q|d)-.*\"}) / sum(redis_up{tenant=~\".*-(q|d)-.*\"})"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ece_deployment_status_elasticsearch_health{location=\"japaneast\", cluster_name=~\".*-(q|d)-.*\"})"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(redis_up{tenant=~\".*-(q|d)-.*\"})"
    }
   ]
  }
 ]
}