apiVersion: v1
kind: Secret
metadata:
    name: otel-secret
    namespace: oe-otel
type: Opaque
data:
    OTLP_USER: ENC[AES256_GCM,data:5+rZyHud4B7STxgP,iv:d83ISnUj9IfOlyyIDS867Pf2/eTBUH/BPX0LNMOPAnk=,tag:il52lzxaONTDa/kXvrI61w==,type:str]
    OTLP_PASSWORD: ENC[AES256_GCM,data:gb0zXzvkJIL257lyvJuGin0KunSKw4KfFriAMIUHT9fyvCtDW8T/tcKdFvs=,iv:jMWECx0YjHI5nPSYsDIe1hKyvdaFu8pEwnITlBxDV50=,tag:wUgvoMdE1bW5yiuPyCf4FQ==,type:str]
    APM_SERVER_TOKEN: ENC[AES256_GCM,data:NrtfLaBwP9N39Fw8od+QKujW6kbI5Faf4Eqy0BL9oQLpE11nnVGD6w==,iv:Vzu/mUbbOrDUdvZOC9sBR16JsgTzB+JNBnvvpQ2ynHI=,tag:wqa68Ag4F/8lIhG6rZzJ9Q==,type:str]
sops:
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2025-07-17T18:20:02Z"
          enc: 4xZFhg1j6YZwSLerMMslKQpiEBZp-GuUVUbXqHZAiVeAMkingIFLbz--VRLHlz8f1gOXHgqjvqjaqMAvsghsCtpaVNhBE74hTvOjxoZSIReAOBu_J_I4haRdoJNYnTSml3FaraxemTQQolQnUU-3IxC-egNYgIMM63BI8LQHpkHI9M3odcVdtT47KVSs8-7uEAzetUtGsFDhj8yBTWchL2x-ijkUaO0kVXd-WoGSHZbej0remuMHwFgWTzKPkDaBMeGfRBiCX-FZS0nEpbyv3ziH4cNvXfGs-qI4pWTiPPmg8_qUsQ0tm2fx8-GdDJqpnb25P5F9KKuK7Sgbq6FUNAMCLPeLf1VKQdxALPLn8jFXtN5xdQzfc4Fw84HcwkG9NMIw5cdPueryoLvJ9viK3TJS78RIamY1E-pzqJKxSy2lH-zryCuJ0u7HcyWVFw5Ve4KVBkykbGFtt153ufg4GLJRqC-F33H-_fI8FQK-agj2fHCGpikZGL4FBA3Bdp1c03upzi3chret2Hk0yDWQPL56DBRfPp9Xq7rMvVo8DSjdqhKKnARc1hJjYWGrfbwGCFDPAsT_GViGoIfetJRgzQdvpvPszxwOX5IKQhw61j8r9y779wwEvngsvJMt2Kn0raEIPTi5lBERk10OL7pvfrkuvNsnZ8JzoDHeoviBAwU
    lastmodified: "2025-07-17T18:20:06Z"
    mac: ENC[AES256_GCM,data:F+XkGQix1eLLK+kFagRffYwiAt7ECB3Yv/CyOomqWPqdW4At85TYZdQTF3q3845QXkEcNJZ/VJTpy1ZDg42EokvEe48GVNSDRG+WuHK0wQmsjUN/7Dne/yZdJzst7LjswewfT+Q7W4QfDIo4s9YdTpCfwoT54K7aljLzbFo2RDg=,iv:Hw6w3h40D2KRydhdqfMA0ETwzi1hx4tgBwAPKb84Ih0=,tag:y0f+aO2VBLPBpKHsLZrChg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
