apiVersion: v1
kind: Secret
metadata:
    name: oe-redis-exporter-hosted-credentials
    namespace: oe-redis-exporter-hosted-c255
type: Opaque
data:
    API_KEY: ENC[AES256_GCM,data:nEa9642tH6bn7FePBO0RIcIc1lk2eEkDF1keww1N/hqSCy6gNQjCOoa4zSM4u5wo5/1A9Jg2xqoQC4Oly72KZ4yXdAI=,iv:pirg1te+/5M1+EOPf6J+L6SoJFXPAMTWfx9TJRvO7rM=,tag:CPiPMIyNCdiuFi7bz2WbDQ==,type:str]
    API_SECRET_KEY: ENC[AES256_GCM,data:n83oXVZWjg95se2kd1nbSzoiLUdpGFXAQTomb35EUIRmibvx/JUNeDfbRerG8AQcB9BpM4eRS6h9mn0a914zYqKf3XQ=,iv:fO31BlovEA9z9DImVMmZZCwg7W5wb7c6w1IT8Gyabzo=,tag:ppiSM/muFLvO2IZAZYxtwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2023-11-24T09:32:31Z"
          enc: Ru86KL_wNm5c_i2RJxtf0bpSNpRz3XZoj5rEBrIL06vkQSfM3gvOX6yp6Ep4ekFEG978dXXNBnrw_PsT3BrhaxNealrB4O6Pntnd1jBo4FocVOVCd9Lb_smxB5M7VlDs9wi3FG_In-26kawH9xt8aUlefGdX7Gc8VMbYoUJ70Oo8e8EjQlTOge_iv-UfszF8bVJsF4nIuZ1f8sfEc3OGkYzjxzPCm7mPKBFoITbYKGEz2vbge-2bjU3CgqtEUHKcNVzD5uPoq-PDaV2OQ9MpzflrDyWsjVGsPlU8sFAsDT7Se5j2VV1nIiyiMtoSCHubVyka1W2mAdtx15RYvABQ46YkWoIP1Vb38MkfFN2nYLPZbAo7YXWD8IzZztVB07sc-T1ntPT7iiMZpaxaGD5Q1jHpZhDjzV5MFFYTE62eyOl5Y8mEFPgzw1DFmIB4itqmKGPfnnT-VCipI4r0L6IqMSJygH23VWkMHr3bqDtxKTD2cfa1WytXuH-ENrigr7ohcisrAUdaLFRrH79JbbBnGDzGxzmJSQtAiorkbu22g60QKtfVfQvoc_gV6e3GIgpoNR0pZJ9aj5DvbrmJiSW9ubmvXCNQxLCYzJ6CkvYUG1f1PhsaIbgBUXkJh5D7-pZrbzHPCI-xd9tcz1X6zUCE9Hrc5SwzrPxpRe25-_Aqz4o
    hc_vault: []
    age: []
    lastmodified: "2023-11-24T09:32:34Z"
    mac: ENC[AES256_GCM,data:Tc1ejHxO9yu7uqMGgtlldVpoqYaOmSBoXhrCFCuctdwUxMct61A6I5kj+pNkvjL2nQ2IADCJDLOuhl/QYFIt9IJ0Qyh61ySBI1wGe11fA95OZy9QssRT1z4CmYUaZD0eRtLDocCeA8szEGgw0woNyKhcJGBnp/gQUYc6Dx4D1AY=,iv:uefi3WPaz32v8T7eFe61VWIqdL4svvesWKMOy05rpB4=,tag:nYONYO+alFNnsnIg0w52XQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
