apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aue-e1-cs-aks-01/
  - aue-e1-shared-aks-01/
  - aue-e1-contenthub-aks-01/
  - aue-e1-contenthub-sb-aks-01/
  - aue-e1-xmcloud-cm-10-aks/
  - aue-e1-xmcloud-cm-11-aks

  
