kind: Secret
metadata:
    name: azure-metrics-exporter
    namespace: oe-azure-metrics-exporter
type: Opaque
apiVersion: v1
data:
    azure-metrics-exporter-app-key: ENC[AES256_GCM,data:wjT6bfa7ztVULKWequavJfEVP4UGfpKHnWkzKGf3QlHaR0M3wqJFieXuCw9Oh4ii1L+foJ9E7lQ=,iv:bEwiIAqk0RmL4HU7Lc/PdJvcz+YXDYFtK0VmbmFOb1M=,tag:YJcXRZ08Esn5vcMP3WsFYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2024-04-08T14:43:13Z"
          enc: FL2UHD8W4dEqSw-PA6UxlqYoLUoKiNn4_8s9_ugQr1deyg60jktqVfFaIaV8SJkkQWMSVAHXfspGyn8ZUXmA-D6gjdFKd-tETZxlxO0mp5WmkSKBdnwes1r2rgLBrEQQ9GizpHo2yWa0WmPYO3Kbtg7cr7VfhMSsraSk7iM13OFU9zeBoW-XRA15Mnx2Jr6H_SIAq_nPGx46fxLTA4tlgNCM9ueHRi2j2zPYkhoyiXiFfhfMeLNX2d_tiLNgYbeW-u9uvDfD-EXF-LMm3HIh-qd9aX7JYB6zFmH2-8BsACuz9x8aqHKHvy8L03p0M8P3MNbj3E7zNuVqPAtj9IYV2rOfA1y-nbvyC5p-bMGsAh9Blc4dxWXo7guNj76iH5DPeua_tKNGHI5UIf9kPLhGPfnZbmJ0JEv2oYnt-Wig7tPlaYujXP7rGHNJZvEgRmoKC69Ru5TnvMPQzNK2sfz0sPfbdIQjQ-Z0HxVyagb7Go_WSVE7AhQxuP_VOQyMPNCZ7WqZIEGyOsIwrO8xep8Jb3NdSoDLQrF9ff3WIdNcAx6t0snHiEfH6P7pIEHm8S103LT9OrJNdkH7IXKNJxJpEB6hq5FcTLlXiLHlENYndqIxqevXIdnbBYV0IOLM1MmIVUDYiNSMDY6jG4Cgt5D7yohhjsBo7jFtUKnPOQ2FVWg
    hc_vault: []
    age: []
    lastmodified: "2024-04-08T14:43:14Z"
    mac: ENC[AES256_GCM,data:rdiAnYmB/N2PvLhmcoZGiowTojIxsIHgs+wQK52Iwrjhb/7B9c7+f24McmmOcMl7NiSZe84HBHn6aD70v59dpPGmjZiKRlabTcVH6VixDdgo/Gbml+oIJmV/mqajrM2OTNmU37mIdGdPJnudTt61bWhKlKH0zJzNcsDFChF6Mhg=,iv:aoZIRX0Pv6/lExw7gyA/GcYy4IHiFtIz72LXNkqZ0hw=,tag:2ExnYMsVabw0SV/+taSs8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
