apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: dora-platform-devlake-mysql
stringData:
    mysql-password: ENC[AES256_GCM,data:uctOBTM=,iv:QouEpCB+a313le2KDqCRIR4289B8f9tTtjaWaCIjjoU=,tag:aUvBXC42QGjpwMgZkEFURA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2023-12-20T05:24:14Z"
          enc: xsq__NQM-N1ulvKHF9e9kKf3WpmL5k36v9UG6y2-Pp9bUpxaZ2lBOxs015I-6hkiuMHIMnuXa34lVsoxtMWtakPGtq_BgUA2iWKghAZyTlIhTp7_0NISUf8L4UTxnSBZACV9borhO-QOBuADRzpMhLjCMAh7siNTNC3bK6eJN7VJ_5b_s4bHDSbRtYD16r2O2iJ0cPUpupO2rIbr8-5FtB90TIEnmqqnscYm2HGYIdqDchktwoz-7YVTO4GpSuKE2dVT0BSYEeryvu7KgMrL_KTITcJWLslBycGrOl9xFRXm1SopJIZZTHPzAivwzlIoM7bh_FZO4hZa68mWy_XuNr_dfm7siUEbR_mb5f94y2mM5NZp66bmOUvYDEJnugrHYmItPQlrzLOwVd0Jxn-I9iVGJVd80sI0XLC8SUb2nw9h0g9pXRebFRad6yDlVrhrw3aCgLzRKXTP36KlobYSDTEZuEECdCjvGjEEtkDqitC4sA51YDUGGIqQRkFeo5LwH1gRe2JdCSFM28ZXC9pGHeqHiNqsfNXhm1Ava0sjpf4JeXtFrl8L4lVfduZuyuya67j2c3lZKRcsAj4ucl9YDLqQg0DTTovS-MKIBZLXOZGn-ZNwNocTZ8N7z5TY-BOVGfq01vcdKcqlFGbjHlf-ApUiNPkvG1L2Tdwv_snD-O4
    hc_vault: []
    age: []
    lastmodified: "2023-12-20T05:24:15Z"
    mac: ENC[AES256_GCM,data:rKw5zAPyrGBhwcZ34hlko0tGXvU7l+c/Ho+/3rdZtWv6rJZ6yOAYDQvFcio1ESGqevp2lrQXsI22xHYp0Pn/1pS+pkfQmq7q1RdmtE618Dck25Uj5e6XD+VteUvM/pwY97V5F2R63UwLFEVxh2lD8L9DZDTi5LlSYeMUas3cYto=,iv:OpWBQbkgwp0zHG2eoo1I2rLRaq+6s/Y31G+ybeWBrOs=,tag:8tYQ0s4anaCD8qZaUz0VOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3