apiVersion: v1
kind: Secret
metadata:
    name: dora-platform-postgresql
stringData:
    postgres-password: ENC[AES256_GCM,data:gM7dqjhwzUFzNlwsuKZLItQ=,iv:/rNyHArr2t8aVTTR29Tac0eJIV8Cn536CKHN7gMl4l4=,tag:JA5Vuo9N87iYQCjRCTBWGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2023-12-19T06:03:12Z"
          enc: PQRd7p4AbTXkPmdbeX--5VZc-gbtcICMD2uox3ivTIkXBmC8kgMvRJiZ_b336Qam_5FCwIhmOQRHp56RdRKkK94on6CyB6gvxZSFsscAxqK3LGv7xY7D_ME9eJDP55MVx32fmbVBNeWiJKcj6yEndYY15LpqvoaDS3C011YGNYaOMW9JPoQMSB5vy5q-FnzEUdu2JA3tXlRtRMhyEqv_gRNJHx1SMJ4uY66Q7cqwg6qMaUKIHe0z_qihZK-UOsVoGuYmyrFmLkp7jpXS3EnxCRDovN31U0e9pnl2I5kzxolADj1e2fXmYWnr4FNuj3r18DMR35eaBhnLIoNcdAC8eejFPL_WR16V-6VzeMUyrYzVytcCUprjOBsQ3VTM1kPwAWpcXm1ONjyLVjvGLd1vgfvN_4-6kUhgSnTblY7axsXHi-fwbY2eYtccRTk23sW5Za9TJ0htsOiJdPar8ii3GCHWz5RxHdQqkGScvSDTxXVC5FQ03H0zM20oljQ0QkCPVgZoyciW2isYO2-ezfmsAugL8RCbsYeHOW3-6FCKrlOODmDpt1eppUpgAJj7xqO4jS2MhaIwjr-tjvwM2RhbYSW3M1vhYX2OIH8FdBy_D9_pVfWa9FsEOfYodNDTdygTix2baUSUYm5foQBdMiTGlPOsaHggyZe1YR-F7TZmchY
    hc_vault: []
    age: []
    lastmodified: "2023-12-19T06:03:13Z"
    mac: ENC[AES256_GCM,data:mOTG2HJi3QWbF4KqlzJ+LDbkoOv8Vmwgr4uEO6SDduQjSjvd1d3HDrqcW2ruUA+t/fAAmZJOb0gU112/Omqr8SyScM9nwi+7V4sf2uk6Rbh2K1DvjQNDv+Kll2waOnBgaZWMMc4BUyTLzZ6n/nm/a0S008aX/YlGZN9v+tjVxLo=,iv:TIAHnnMvdl+qKbvE09rV2RROol1nC61bTcHUL3S2YCs=,tag:i08WxC8o7jdYWIgw8d3UWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3