apiVersion: v1
kind: Secret
metadata:
    name: postgres
type: Opaque
data:
    username: ENC[AES256_GCM,data:47jzdqcrqHo/21mv,iv:JLLE9j0MlT7UEIoMZBLnlIhRsC1140v6i/dJ33Bf/7s=,tag:MMCszrSQuwHYL1NG+5/Wsg==,type:str]
    postgres-password: ENC[AES256_GCM,data:gXQTQINi0leM2yZvK04TjAZ+9qcR9Jm2,iv:++lRczWh59GFJLodvonI6bUHfQz2XsWgOOgk8jN6W4A=,tag:QulrBToRjnwzy4uSkosIAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://global-e1-sopskv-01.vault.azure.net
          name: sops-key
          version: b8ecad3de3b6456e8ec9c6aff1c6c8b2
          created_at: "2023-12-19T05:37:03Z"
          enc: MI2tK2Viwt9YSHSijrCCWeh5KblE0nwxg4f5jWdgqqdgheVviF_7-ngnu_M4R1Walihzrl_POaHpUNaccZ1s7pZ6eLaaMx6Jed44FX9uiInjlZ08GMJb8yu__ooxKSfxRuTzmNWWjrk1zG4EmxyVvRM9oj3BWheFSi5sqaNWXazUMDzza5u4lDbCV8nenYGEl-xDLMBA60PL40N2b7cWtj1K7m-rvppZyA7cjxo_C58gy10sj6Afwb7qjbK1T2DfMgoAv2H2vhTC7Mxk0b6OpnTTMgyJzj3hCtzmKm-7UVuOwX4l1a_UJPVSrBMrJ52Enit2B0Wv98xEasAmaXOUJ0WK2uP3PCVeXF677mWSZzHfPtnX9c3-ECX3k9Jkn4msBApDPV0S07N4uEXd2Exp8Tk66xVrRX4UY0J3kVKMPLt0KdA144Pv4M37HMZ2CX3KCFDz6mUQUdUFxmj1Oqvf8hIR4UMzI3yunGIEwVsLkt8CImLoW7yvNUitVPnyPLjVydfW7aY-kG3iHx1wt_X3wCYiC-u9Wh0xHoAUWcNK404r_QbjVoQZjptejUcu7qFiM7nRsn2ovBPQt3MbBeOM_yAXDewlt9P25aiL0Zkx09kW1EqyZ1M2eFb0gJW_cZqvHr69HYRe_ALBcv795dRIKlFxWZxl79iSMvFLA5suCn8
    hc_vault: []
    age: []
    lastmodified: "2023-12-19T05:37:04Z"
    mac: ENC[AES256_GCM,data:q8VaSm2eHnwsmn0zTpv9j0RbaLP7VE3dK93YGNT80ppJu80MNXqhq075mQR5v4Mkpbv5ZEGoh8493EJFYHrS3eR4KCK1/xfQsOCx5uZ2uC+8iNTvxR3wd0B62RBHSRj+CvTuCERgZr7HsUzH9zcItk+9IBZOZupjbsq8kiVocks=,iv:6UoMKjcDIPArBsqnhwOeJfuqqrk09bFim4NwJRsAkKM=,tag:PJn7ld4ab0plz/VnMDrmTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3