---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pyroscope-stack
spec:
  interval: 1h0m0s
  chart:
    spec:
      version: 1.14.0
      chart: pyroscope
      sourceRef:
        kind: HelmRepository
        name: pyroscope-stack
        namespace: oe-pyroscope
  valuesFrom:
    - kind: ConfigMap
      name: helm-values-pyroscope-stack-base
      valuesKey: values.yaml
  upgrade:
    remediation:
      strategy: rollback
      retries: 3
