name: Docker Image Push
on:
  push:
    branches:
      - "main"
    paths:
      - "grafana/Dockerfile"
      - "grafana/docker-compose.yml"
      - ".simpleversion.json"
      - ".github/workflows/docker-image-push.yaml"
  workflow_dispatch:

# Stop existing run if workflow and branch are the same. For master branch, the build is cancelled if both builds have the same workflow and commit hash.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name != 'main' && github.ref_name || github.sha }}
  cancel-in-progress: true

jobs:
  calculate-version:
    uses: Sitecore-Internal/sitecore.devops.github.workflow.simpleversion/.github/workflows/SimpleVersion.yaml@V2
    secrets: inherit

  build-push-docker-image:
    needs:
      - calculate-version
    uses: Sitecore-Internal/sitecore.devops.github.workflow.dockerbuildandpush/.github/workflows/DockerBuildAndPush.yaml@V2
    # TODO: Change to V3
    secrets: inherit
    with:
      Version: ${{ needs.calculate-version.outputs.version }}
      DockerNamespace: grafana
      ComposeFile: grafana/docker-compose.yml
      ScanServices: grafana-silences-creation-image
      DockerRegistry: weui1heimdal01acr.azurecr.io